services:
  qdrant-database:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - ".:/qdrant/storage"
  flask:
    build: 
      context: .
      dockerfile: Dockerfile
    image: irs/irsystem:lastest
    ports:
      - "8000:8000"
    # container_name: xenodochial_jemison
    # restart: always
    volumes:
      - ".:/opt/irs/static"
    environment:
      - APP_QDRANT__HOST=qdrant-database
      - APP_QDRANT__PORT=6333
      - APP_QDRANT__GRPC_PORT=6334
      - APP_QDRANT__PREFER_GRPC=True
    depends_on:
      - qdrant-database
networks:
  default:
    name: irs