# services:
#   qdrant-database:
#     image: qdrant/qdrant:latest
#     ports:
#       - "127.0.0.1:6333:6333"
#       - "127.0.0.1:6334:6334"
#     volumes:
#       - "./qdrant_data:/qdrant/storage:"
#   neko-image-gallery:
#     # Uncomment this section to build image from source code
#     build:
#       context: .
#       dockerfile: Dockerfile
#     image: edgeneko/neko-image-gallery:latest
#     ports:
#       - "127.0.0.1:8000:8000"
#     volumes:
#       - "./static:/opt/NekoImageGallery/static"
#     environment:
#       - APP_QDRANT__HOST=qdrant-database
#       - APP_QDRANT__PORT=6333
#       - APP_QDRANT__GRPC_PORT=6334
#       - APP_QDRANT__PREFER_GRPC=True
#     depends_on:
#       - qdrant-database
#     deploy:
#       resources:
#         reservations:
#           devices:
#             - driver: nvidia
#               count: 1
#               capabilities:
#                 - gpu
# networks:
#   default:
#     name: neko-image-gallery

services:
  qdrant-database:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - ".:/qdrant/storage"
  flask:
    build: 
      context: .
      dockerfile: Dockerfile
    image: irs/irsystem:lastest
    ports:
      - "8000:8000"
    # container_name: xenodochial_jemison
    # restart: always
    volumes:
      - ".:/opt/irs/static"
    environment:
      - APP_QDRANT__HOST=qdrant-database
      - APP_QDRANT__PORT=6333
      - APP_QDRANT__GRPC_PORT=6334
      - APP_QDRANT__PREFER_GRPC=True
    depends_on:
      - qdrant-database
networks:
  default:
    name: irs